default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: db   # or 'postgres' if your service is named that
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: marketplace_service_development

test:
  <<: *default
  database: marketplace_service_test

production:
  <<: *default
  database: marketplace_service_production
  username: postgres
  password: password
  host: db   # or 'postgres'
  port: 5432
